/*
 * JGetXML.java
 *
 * Created on 2007717, 1:08
 */

package edu.frank.swing.framework.JBasicSource;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import java.util.List;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;

import org.jdom.input.SAXBuilder;
import org.jdom.output.XMLOutputter;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.Attributes;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

/**
 *
 * @author  yoyudenghihi
 */
public class JGetXML extends javax.swing.JFrame {

    /** Creates new form JGetXML */
    public JGetXML() {
        initComponents();

        //
        m_width = getWidth();
        m_height = getHeight();
        int x = (toolkit.getScreenSize().width-m_width)/2;
        int y = (toolkit.getScreenSize().height-m_height)/2;
        this.setBounds(x,y,m_width,m_height);

        //
        try
        {
            File file = new File("src/org/txt/JGetXML.txt");
            FileReader fr = new FileReader(file);
            jTextArea1.read(fr,null);
        }catch(Exception e){jTextArea1.setText("");}

        setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\u83b7\u53d6XML\u6570\u636e");
        jLabel1.setFont(new java.awt.Font("", 0, 18));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("JDOM\u83b7\u53d6XML\u6570\u636e");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 3, true), "\u63d0\u793a\u4fe1\u606f:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 13), new java.awt.Color(0, 0, 255)));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("", 0, 15));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 3, true), "XML\u4fe1\u606f:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 13), new java.awt.Color(51, 51, 255)));
        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true), "\u64cd\u4f5c\uff1a", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 13), new java.awt.Color(51, 51, 255)));
        jButton1.setText("DOM\u5904\u7406");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SAX\u5904\u7406");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("JDOM\u5904\u7406");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("\u91cd\u65b0\u8bfb\u5165XML\u6587\u6863");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton4))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton2)
                            .add(jButton3)
                            .add(jButton1))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(57, 57, 57)
                .add(jButton1)
                .add(81, 81, 81)
                .add(jButton2)
                .add(84, 84, 84)
                .add(jButton3)
                .add(71, 71, 71)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(60, 60, 60))
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 3, true), "\u8f93\u51fa\u4fe1\u606f:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 13), new java.awt.Color(51, 51, 255)));
        jTextArea3.setColumns(20);
        jTextArea3.setEditable(false);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        jMenu1.setText("Operator(O)");
        jMenuItem1.setMnemonic('X');
        jMenuItem1.setText("Exit(X)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 323, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 224, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO 
        //XML
        try
        {
            File file1 = new File("src/org/txt/RDemo.xml");
            File file2 = new File("src/org/txt/Demo.xml");
            FileReader fr = new FileReader(file1);
            FileWriter wr = new FileWriter(file2);
            jTextArea2.read(fr,null);
            jTextArea2.write(wr);
        }catch(Exception e){jTextArea2.setText("XML");}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO 
         //
        jTextArea3.setText("");
        File file;
        SAXBuilder builder;
        org.jdom.Document doc;
        try
        {
            //XML
             file = new File("src/org/txt/Demo.xml");
            //builderbuilderXML
             builder = new SAXBuilder();
             doc = builder.build(file);
              //XML
             org.jdom.Element root = doc.getRootElement();
             //XML
             List list = root.getChildren();
             //
             for(Iterator iter = list.iterator();iter.hasNext();)
             {
                 //
                 org.jdom.Element element = (org.jdom.Element)iter.next();
                 //
                 String nodeName = element.getName();
                 //"address"
                 if(nodeName.equals("address"))
                 {
                     //"country","China"
                     org.jdom.Element country = new org.jdom.Element("country");
                     country.addContent("China");
                     element.addContent(country);

                     //"street"
                     org.jdom.Element street = element.getChild("street");
                     street.setText("BUPT,10# XiTuCheng road");

                     //"district"
                     element.removeChild("district");
                 }
             }
             try
             {
                 //XML
                 XMLOutputter fmt = new XMLOutputter();
                 //
                 FileWriter writer = new FileWriter("src/org/txt/Demo.xml");
                 //XML
                 //Format f = Format.getPrettyFormat();
                 //fmt.setFormat(f);
                 //XMLXML
                 fmt.output(doc,writer);
                 writer.close();
                 FileReader fr = new FileReader("src/org/txt/Demo.xml");
                 jTextArea3.read(fr,null);
             }
             catch(Exception e){jTextArea3.setText("XML");}
        }
        catch(IOException e1){jTextArea3.setText("XML");}
        catch(Exception e2){jTextArea3.setText("XML");}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO 
        //
        jTextArea3.setText("");
        try
        {
            //SAXParserFactoryfactory
            SAXParserFactory factory = SAXParserFactory.newInstance();
            //SAXParserFactoryfactorynewSAXParser()SAX
            SAXParser saxParser = factory.newSAXParser();
            //
            MyHandler myHandler = new MyHandler();
            //SAXparse()XML
            saxParser.parse(new InputSource("src/org/txt/Demo.xml"),myHandler);
        }
        catch(SAXException e1){jTextArea3.setText("XML");}
        catch(Exception e2){jTextArea3.setText("XML");}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO 
        //
        jTextArea3.setText("");
        //FilefileXML
        File file = new File("src/org/txt/Demo.xml");
        //DocumentBuilderFactorynewInstance()factory
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        try
        {
            //factorynewDocumentBuilder()DocumentBuilder
            DocumentBuilder builder = factory.newDocumentBuilder();

            //DocumentBuilderparse()XMLDocument
            org.w3c.dom.Document doc = builder.parse(file);

            //docgetDocumentElement()
            org.w3c.dom.Element element1 = doc.getDocumentElement();
            //elementgetNodeName()
            String str = element1.getNodeName();
            jTextArea3.append(":  "+str+"\n");

            //element1getElementsByTagName(),
            //"name"list
            NodeList list = element1.getElementsByTagName("name");
            //getLength()
            int n = list.getLength();
            //"name"
            jTextArea3.append("name:"+"\n");
            for(int i = 0;i < n; i++)
            {
                //"name"
                Node node = list.item(i);
                //
                String value = node.getNodeValue();
             jTextArea3.append(value+"\n");
            }
        }
        catch(Exception e){jTextArea3.setText("XML");};
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO 
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    //
    class MyHandler extends DefaultHandler
    {
        //
        @Override
		public void startElement(String namespace,String lname,String qname,Attributes att)
        {
            //
            if(att!=null)   //
            {
                for(int i=0;i<att.getLength();i++)
                {
                    //
                    jTextArea3.append(":  "+qname+"\n");
                    if(att.getQName(i).equals("familyname"))
                    {
                        //"familyname"
                        jTextArea3.append(":  "+att.getQName(i)+", :  "+att.getValue(i)+"\n");
                    }
                }

            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JGetXML().setVisible(true);
            }
        });
    }

    //  - //GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // //GEN-END:variables
    private int m_height,m_width;
    private Toolkit toolkit =getToolkit();
}