/*
 * JLocale.java
 *
 * Created on 2007625, 12:20
 */

package edu.frank.swing.framework.JBasicSource;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;
/**
 *
 * @author  yoyudenghihi
 */
public class JLocale extends javax.swing.JFrame {
    /** Creates new form JLocale */
    public JLocale() {
        initComponents();
        //
        m_width = getWidth();
        m_height = getHeight();
        int x = (toolkit.getScreenSize().width-m_width)/2;
        int y = (toolkit.getScreenSize().height-m_height)/2;
        this.setBounds(x,y,m_width,m_height);
        //
        try
        {
            File file = new File("src/org/txt/JLocale.txt");
            FileReader fr = new FileReader(file);
            jTextArea1.read(fr,null);
        }catch(Exception e){jTextArea1.setText("");}
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        flag = 0;
        date = new Date();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\u56fd\u9645\u5316\u548c\u672c\u5730\u5316\u5b9e\u4f8b");
        setResizable(false);
        jLabel1.setFont(new java.awt.Font("Serif", 1, 24));
        jLabel1.setText("Java\u56fd\u9645\u5316\u548c\u672c\u5730\u5316");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true), "\u63d0\u793a\uff1a", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 13), new java.awt.Color(0, 0, 255)));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("_GB2312", 0, 15));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true), "\u64cd\u4f5c\uff1a", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 13), new java.awt.Color(0, 0, 255)));
        jLabel2.setText("\u5730\u533a\u9009\u62e9\uff1a");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("\u4e2d\u56fd");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("\u7f8e\u56fd");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("\u65e5\u672c");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("\u6cd5\u56fd");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });

        jLabel3.setText("\u683c\u5f0f\u5316\u5185\u5bb9\uff1a");

        jRadioButton5.setText("\u7b26\u53f7");
        jRadioButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton5ItemStateChanged(evt);
            }
        });

        jRadioButton6.setText("\u65e5\u671f");
        jRadioButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton6ItemStateChanged(evt);
            }
        });

        jRadioButton7.setText("\u8bed\u8a00-\"Hello World\"");
        jRadioButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton7ItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jRadioButton1)
                            .add(jRadioButton2))
                        .add(22, 22, 22)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jRadioButton4)
                            .add(jRadioButton3)))
                    .add(jLabel3)
                    .add(jRadioButton5)
                    .add(jRadioButton6)
                    .add(jRadioButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton1)
                    .add(jRadioButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton2)
                    .add(jRadioButton4))
                .add(19, 19, 19)
                .add(jLabel3)
                .add(19, 19, 19)
                .add(jRadioButton5)
                .add(17, 17, 17)
                .add(jRadioButton6)
                .add(17, 17, 17)
                .add(jRadioButton7)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 1, true), "\u7ed3\u679c\uff1a", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 13), new java.awt.Color(0, 0, 255)));
        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Courier", 1, 15));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jMenu1.setText("Options(O)");
        jMenuItem1.setMnemonic('X');
        jMenuItem1.setText("Exit(X)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(188, 188, 188)
                        .add(jLabel1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 288, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jLabel1)
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
// TODO 
     jTextArea2.setText("");
     locale = new Locale("fr","FR");
     jTextArea2.append("Locale(_ISO-3166):  "+locale.toString()+"\n");
     jTextArea2.append(":  "+locale.getDisplayCountry()+"\n");
     jTextArea2.append("(ISO-3166):  "+locale.getLanguage()+"\n");
     jTextArea2.append("(ISO-3166):  "+locale.getCountry()+"\n");
     jTextArea2.append(":  "+locale.getVariant()+"\n");
     jTextArea2.append(":  "+locale.getDisplayVariant()+"\n");
     flag = 4;
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
// TODO 
     jTextArea2.setText("");
     locale = new Locale("ja","JP");
     jTextArea2.append("Locale(_ISO-3166):  "+locale.toString()+"\n");
     jTextArea2.append(":  "+locale.getDisplayCountry()+"\n");
     jTextArea2.append("(ISO-3166):  "+locale.getLanguage()+"\n");
     jTextArea2.append("(ISO-3166):  "+locale.getCountry()+"\n");
     jTextArea2.append(":  "+locale.getVariant()+"\n");
     jTextArea2.append(":  "+locale.getDisplayVariant()+"\n");
     flag = 3;
    }//GEN-LAST:event_jRadioButton3ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
     // TODO 
     jTextArea2.setText("");
     locale = new Locale("en","US");
     jTextArea2.append("Locale(_ISO-3166):  "+locale.toString()+"\n");
     jTextArea2.append(":  "+locale.getDisplayCountry()+"\n");
     jTextArea2.append("(ISO-3166):  "+locale.getLanguage()+"\n");
     jTextArea2.append("(ISO-3166):  "+locale.getCountry()+"\n");
     jTextArea2.append(":  "+locale.getVariant()+"\n");
     jTextArea2.append(":  "+locale.getDisplayVariant()+"\n");
     flag = 2;
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jRadioButton7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton7ItemStateChanged
// TODO 
       /* ResourceBundle bundle;
        String value;
        switch(flag)
        {
            case 1:
                 bundle = ResourceBundle.getBundle("CHINESE");
                 value = bundle.getString("helloworld");
                jTextArea2.append(":  "+value+"\n");
                break;
            case 2:
                 bundle = ResourceBundle.getBundle("ENGLISH");
                 value = bundle.getString("helloworld");
                jTextArea2.append(":  "+value+"\n");
                break;
            case 3:
                bundle = ResourceBundle.getBundle("JAPANESE");
                value = bundle.getString("hello");
                jTextArea2.append(":  "+value+"\n");
                break;
            case 4:
                bundle = ResourceBundle.getBundle("FRENCH");
                value = bundle.getString("helloworld");
                jTextArea2.append(":  "+value+"\n");
                break;
            default:
                break;
        }*/
    }//GEN-LAST:event_jRadioButton7ItemStateChanged

    private void jRadioButton5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton5ItemStateChanged
// TODO 
        double money = 3000.00;
        double number = 1000.0/3.0;
        switch(flag)
        {
            case 1:
                showMoney(money,Locale.CHINA);
                showNumber(number,Locale.CHINA);
                break;
            case 2:
                showMoney(money,Locale.US);
                showNumber(number,Locale.US);
                break;
            case 3:
                showMoney(money,Locale.JAPAN);
                showNumber(number,Locale.JAPAN);
                break;
            case 4:
                showMoney(money,Locale.FRANCE);
                showNumber(number,Locale.FRANCE);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jRadioButton5ItemStateChanged

    private void jRadioButton6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton6ItemStateChanged
     // TODO 
        switch(flag)
        {
            case 1:
                showDate(date,DateFormat.DEFAULT,Locale.CHINA);
                showTime(date,DateFormat.DEFAULT,Locale.CHINA);
                break;
            case 2:
                showDate(date,DateFormat.DEFAULT,Locale.US);
                showTime(date,DateFormat.DEFAULT,Locale.US);
                break;
            case 3:
                showDate(date,DateFormat.DEFAULT,Locale.JAPAN);
                showTime(date,DateFormat.DEFAULT,Locale.JAPAN);
                break;
            case 4:
                showDate(date,DateFormat.DEFAULT,Locale.FRANCE);
                showTime(date,DateFormat.DEFAULT,Locale.FRANCE);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jRadioButton6ItemStateChanged

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
    // TODO 
     jTextArea2.setText("");
     locale = new Locale("zh","CN");
     jTextArea2.append("Locale(_ISO-3166):  "+locale.toString()+"\n");
     jTextArea2.append(":  "+locale.getDisplayCountry()+"\n");
     jTextArea2.append("(ISO-3166):  "+locale.getLanguage()+"\n");
     jTextArea2.append("(ISO-3166):  "+locale.getCountry()+"\n");
     jTextArea2.append(":  "+locale.getVariant()+"\n");
     jTextArea2.append(":  "+locale.getDisplayVariant()+"\n");
     flag = 1;
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     dispose();// TODO 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLocale().setVisible(true);
            }
        });
    }

    public void showDate(Date date,int datestyle,Locale locale){
        DateFormat currentDateFormat = DateFormat.getDateInstance(datestyle,locale);
        String datestring  = currentDateFormat.format(date);
        jTextArea2.append(": "+datestring+"\n");
    }
    public void showTime(Date date,int datestyle,Locale locale){
        DateFormat currentDateFormat = DateFormat.getTimeInstance(datestyle,locale);
        String timestring = currentDateFormat.format(date);
        jTextArea2.append(": "+timestring+"\n");
    }
    public void showMoney(double money,Locale locale){
        NumberFormat numberFormat = NumberFormat.getCurrencyInstance(locale);
        String str = numberFormat.format(money);
        jTextArea2.append(":"+str+"\n");
    }
    public void showNumber(double num,Locale locale){
        NumberFormat numberFormat = NumberFormat.getIntegerInstance(locale);
        numberFormat.setMaximumFractionDigits(5);
        String str = numberFormat.format(num);
        jTextArea2.append(":"+str+"\n");
    }

    //  - //GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // //GEN-END:variables
    private int m_height,m_width;
    private Toolkit toolkit =getToolkit();
    Locale locale;
    Date date;
    int flag;
}