/*
 * JGui.java
 *
 * Created on 2007616, 1:25
 */

package edu.frank.swing.framework.JGUISource;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import org.apache.log4j.Logger;

import edu.frank.log4j.Log4JConfig;
import edu.frank.swing.framework.JSwingMain;

/**
 *
 * @author  yoyudenghihi
 */
public class JGui extends javax.swing.JFrame {

	/**
	 * Class serializable id
	 *
	 * @since JavaBasic 1.0.0.0
	 */
	private static final long serialVersionUID = -7688722548667029737L;

	/**
	 * Logger record object
	 *
	 * @since JavaBasic 1.0.0.0
	 */
	private static final Logger logger = Log4JConfig.getLogger(JGui.class);

	/**
	 *
	 * construct a new <code>JGui</code> instance for class
	 *
	 * @since JavaBasic 1.0.0.0
	 */
	public JGui() {
		initComponents();
		//
		this.m_width = getWidth();
		this.m_height = getHeight();
		int x = (this.toolkit.getScreenSize().width - this.m_width) / 2;
		int y = (this.toolkit.getScreenSize().height - this.m_height) / 2;
		this.setBounds(x, y, this.m_width, this.m_height);
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		this.jLabel1 = new javax.swing.JLabel();
		this.jScrollPane1 = new javax.swing.JScrollPane();
		this.jTextArea1 = new javax.swing.JTextArea();
		this.jMenuBar1 = new javax.swing.JMenuBar();
		this.jMenu1 = new javax.swing.JMenu();
		this.jMenuItem1 = new javax.swing.JMenuItem();
		this.jMenu2 = new javax.swing.JMenu();
		this.jMenuItem2 = new javax.swing.JMenuItem();
		this.jMenuItem3 = new javax.swing.JMenuItem();
		this.jSeparator2 = new javax.swing.JSeparator();
		this.jMenuItem4 = new javax.swing.JMenuItem();
		this.jMenu3 = new javax.swing.JMenu();
		this.jMenuItem5 = new javax.swing.JMenuItem();
		this.jMenuItem6 = new javax.swing.JMenuItem();
		this.jSeparator1 = new javax.swing.JSeparator();
		this.jMenuItem7 = new javax.swing.JMenuItem();
		this.jMenuItem8 = new javax.swing.JMenuItem();
		this.jSeparator3 = new javax.swing.JSeparator();
		this.jMenuItem9 = new javax.swing.JMenuItem();
		this.jMenuItem10 = new javax.swing.JMenuItem();
		this.jMenu4 = new javax.swing.JMenu();
		this.jMenuItem26 = new javax.swing.JMenuItem();
		this.jSeparator9 = new javax.swing.JSeparator();
		this.jMenuItem27 = new javax.swing.JMenuItem();
		this.jMenuItem28 = new javax.swing.JMenuItem();
		this.jMenuItem29 = new javax.swing.JMenuItem();
		this.jMenuItem30 = new javax.swing.JMenuItem();
		this.jSeparator10 = new javax.swing.JSeparator();
		this.jMenuItem32 = new javax.swing.JMenuItem();
		this.jMenuItem33 = new javax.swing.JMenuItem();
		this.jMenuItem34 = new javax.swing.JMenuItem();
		this.jSeparator11 = new javax.swing.JSeparator();
		this.jMenuItem35 = new javax.swing.JMenuItem();
		this.jMenuItem36 = new javax.swing.JMenuItem();
		this.jSeparator12 = new javax.swing.JSeparator();
		this.jMenuItem31 = new javax.swing.JMenuItem();
		this.jMenuItem37 = new javax.swing.JMenuItem();
		this.jSeparator13 = new javax.swing.JSeparator();
		this.jMenuItem38 = new javax.swing.JMenuItem();
		this.jMenuItem39 = new javax.swing.JMenuItem();
		this.jSeparator14 = new javax.swing.JSeparator();
		this.jMenuItem40 = new javax.swing.JMenuItem();
		this.jSeparator15 = new javax.swing.JSeparator();
		this.jMenuItem41 = new javax.swing.JMenuItem();
		this.jMenuItem42 = new javax.swing.JMenuItem();
		this.jMenu5 = new javax.swing.JMenu();
		this.jMenuItem11 = new javax.swing.JMenuItem();
		this.jSeparator4 = new javax.swing.JSeparator();
		this.jMenuItem12 = new javax.swing.JMenuItem();
		this.jMenu6 = new javax.swing.JMenu();
		this.jMenuItem13 = new javax.swing.JMenuItem();
		this.jMenuItem14 = new javax.swing.JMenuItem();
		this.jMenuItem15 = new javax.swing.JMenuItem();
		this.jSeparator5 = new javax.swing.JSeparator();
		this.jMenuItem16 = new javax.swing.JMenuItem();
		this.jMenuItem17 = new javax.swing.JMenuItem();
		this.jMenuItem18 = new javax.swing.JMenuItem();
		this.jSeparator6 = new javax.swing.JSeparator();
		this.jMenuItem19 = new javax.swing.JMenuItem();
		this.jMenu7 = new javax.swing.JMenu();
		this.jMenuItem20 = new javax.swing.JMenuItem();
		this.jMenuItem21 = new javax.swing.JMenuItem();
		this.jMenuItem22 = new javax.swing.JMenuItem();
		this.jSeparator7 = new javax.swing.JSeparator();
		this.jMenuItem23 = new javax.swing.JMenuItem();
		this.jMenuItem24 = new javax.swing.JMenuItem();
		this.jSeparator8 = new javax.swing.JSeparator();
		this.jMenuItem25 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("JAVAGUI");

		this.jLabel1.setFont(new java.awt.Font("Serif", 1, 12));
		this.jLabel1.setForeground(new java.awt.Color(0, 0, 255));
		this.jLabel1.setText("\u4ee3\u7801\u67e5\u770b\u7a97\u53e3:");

		this.jTextArea1.setColumns(20);
		this.jTextArea1.setEditable(false);
		this.jTextArea1.setFont(new java.awt.Font("Courier", 0, 15));
		this.jTextArea1.setRows(5);
		this.jScrollPane1.setViewportView(this.jTextArea1);

		this.jMenu1.setMnemonic('O');
		this.jMenu1.setText("\u64cd\u4f5c(O)");

		this.jMenuItem1.setMnemonic('X');
		this.jMenuItem1.setText("\u9000\u51fa(X)");
		this.jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		this.jMenu1.add(this.jMenuItem1);

		this.jMenuBar1.add(this.jMenu1);

		this.jMenu2.setMnemonic('F');
		this.jMenu2.setText("\u7a97\u53e3(F)");

		this.jMenuItem2.setMnemonic('F');
		this.jMenuItem2.setText("JFrame(F)");
		this.jMenu2.add(this.jMenuItem2);

		this.jMenuItem3.setMnemonic('W');
		this.jMenuItem3.setText("JWindow(W)");
		this.jMenu2.add(this.jMenuItem3);
		this.jMenu2.add(this.jSeparator2);

		this.jMenuItem4.setMnemonic('D');
		this.jMenuItem4.setText("JDialog(D)");
		this.jMenu2.add(this.jMenuItem4);

		this.jMenuBar1.add(this.jMenu2);

		this.jMenu3.setMnemonic('P');
		this.jMenu3.setText("\u9762\u677f(P)");

		this.jMenuItem5.setMnemonic('P');
		this.jMenuItem5.setText("JPane(P)");
		this.jMenu3.add(this.jMenuItem5);

		this.jMenuItem6.setMnemonic('S');
		this.jMenuItem6.setText("JScrollPane(S)");
		this.jMenu3.add(this.jMenuItem6);
		this.jMenu3.add(this.jSeparator1);

		this.jMenuItem7.setMnemonic('E');
		this.jMenuItem7.setText("JEditPane(E)");
		this.jMenu3.add(this.jMenuItem7);

		this.jMenuItem8.setMnemonic('T');
		this.jMenuItem8.setText("JTabbedPane(T)");
		this.jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem8ActionPerformed(evt);
			}
		});
		this.jMenu3.add(this.jMenuItem8);
		this.jMenu3.add(this.jSeparator3);

		this.jMenuItem9.setMnemonic('D');
		this.jMenuItem9.setText("JDestopPane(D)");
		this.jMenu3.add(this.jMenuItem9);

		this.jMenuItem10.setMnemonic('L');
		this.jMenuItem10.setText("JSplitPane(L)");
		this.jMenu3.add(this.jMenuItem10);

		this.jMenuBar1.add(this.jMenu3);

		this.jMenu4.setMnemonic('A');
		this.jMenu4.setText("\u5e38\u7528\u7ec4\u4ef6(A)");

		this.jMenuItem26.setMnemonic('A');
		this.jMenuItem26.setText("JLabel(A)");
		this.jMenu4.add(this.jMenuItem26);
		this.jMenu4.add(this.jSeparator9);

		this.jMenuItem27.setMnemonic('B');
		this.jMenuItem27.setText("JButton(B)");
		this.jMenu4.add(this.jMenuItem27);

		this.jMenuItem28.setMnemonic('C');
		this.jMenuItem28.setText("JCheckBox(C)");
		this.jMenu4.add(this.jMenuItem28);

		this.jMenuItem29.setMnemonic('D');
		this.jMenuItem29.setText("JRadioButton(D)");
		this.jMenu4.add(this.jMenuItem29);

		this.jMenuItem30.setMnemonic('E');
		this.jMenuItem30.setText("JComboBox(E)");
		this.jMenu4.add(this.jMenuItem30);
		this.jMenu4.add(this.jSeparator10);

		this.jMenuItem32.setMnemonic('F');
		this.jMenuItem32.setText("JTextField(F)");
		this.jMenu4.add(this.jMenuItem32);

		this.jMenuItem33.setMnemonic('G');
		this.jMenuItem33.setText("JPasswordField(G)");
		this.jMenu4.add(this.jMenuItem33);

		this.jMenuItem34.setMnemonic('H');
		this.jMenuItem34.setText("JTextArea(H)");
		this.jMenu4.add(this.jMenuItem34);
		this.jMenu4.add(this.jSeparator11);

		this.jMenuItem35.setMnemonic('I');
		this.jMenuItem35.setText("JSlider(I)");
		this.jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem35ActionPerformed(evt);
			}
		});
		this.jMenu4.add(this.jMenuItem35);

		this.jMenuItem36.setMnemonic('J');
		this.jMenuItem36.setText("JProgressBar(J)");
		this.jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem36ActionPerformed(evt);
			}
		});
		this.jMenu4.add(this.jMenuItem36);
		this.jMenu4.add(this.jSeparator12);

		this.jMenuItem31.setMnemonic('K');
		this.jMenuItem31.setText("JList(K)");
		this.jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem31ActionPerformed(evt);
			}
		});
		this.jMenu4.add(this.jMenuItem31);

		this.jMenuItem37.setMnemonic('L');
		this.jMenuItem37.setText("JTable(L)");
		this.jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem37ActionPerformed(evt);
			}
		});
		this.jMenu4.add(this.jMenuItem37);
		this.jMenu4.add(this.jSeparator13);

		this.jMenuItem38.setMnemonic('M');
		this.jMenuItem38.setText("JFileChooser(M)");
		this.jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem38ActionPerformed(evt);
			}
		});
		this.jMenu4.add(this.jMenuItem38);

		this.jMenuItem39.setMnemonic('N');
		this.jMenuItem39.setText("JColorChooser(N)");
		this.jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem39ActionPerformed(evt);
			}
		});
		this.jMenu4.add(this.jMenuItem39);
		this.jMenu4.add(this.jSeparator14);

		this.jMenuItem40.setMnemonic('O');
		this.jMenuItem40.setText("JTree(O)");
		this.jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem40ActionPerformed(evt);
			}
		});
		this.jMenu4.add(this.jMenuItem40);
		this.jMenu4.add(this.jSeparator15);

		this.jMenuItem41.setMnemonic('P');
		this.jMenuItem41.setText("JMenu(P)");
		this.jMenu4.add(this.jMenuItem41);

		this.jMenuItem42.setMnemonic('Q');
		this.jMenuItem42.setText("JToolBar(Q)");
		this.jMenu4.add(this.jMenuItem42);

		this.jMenuBar1.add(this.jMenu4);

		this.jMenu5.setMnemonic('L');
		this.jMenu5.setText("\u5c0f\u5e94\u7528\u7a0b\u5e8f(L)");

		this.jMenuItem11.setMnemonic('A');
		this.jMenuItem11.setText("Applet(A)");
		this.jMenu5.add(this.jMenuItem11);
		this.jMenu5.add(this.jSeparator4);

		this.jMenuItem12.setMnemonic('P');
		this.jMenuItem12.setText("JApplet(P)");
		this.jMenu5.add(this.jMenuItem12);

		this.jMenuBar1.add(this.jMenu5);

		this.jMenu6.setMnemonic('Y');
		this.jMenu6.setText("\u5e03\u5c40(Y)");

		this.jMenuItem13.setMnemonic('F');
		this.jMenuItem13.setText("FlowLayout(F)");
		this.jMenu6.add(this.jMenuItem13);

		this.jMenuItem14.setMnemonic('B');
		this.jMenuItem14.setText("BorderLayout(B)");
		this.jMenu6.add(this.jMenuItem14);

		this.jMenuItem15.setMnemonic('G');
		this.jMenuItem15.setText("GridLayout(G)");
		this.jMenu6.add(this.jMenuItem15);
		this.jMenu6.add(this.jSeparator5);

		this.jMenuItem16.setMnemonic('(');
		this.jMenuItem16.setText("GridbagLayout(R)");
		this.jMenu6.add(this.jMenuItem16);

		this.jMenuItem17.setMnemonic('C');
		this.jMenuItem17.setText("CardLayout(C)");
		this.jMenu6.add(this.jMenuItem17);

		this.jMenuItem18.setMnemonic('O');
		this.jMenuItem18.setText("BoxLayout(O)");
		this.jMenu6.add(this.jMenuItem18);
		this.jMenu6.add(this.jSeparator6);

		this.jMenuItem19.setMnemonic('U');
		this.jMenuItem19.setText("GroupLayout(U)");
		this.jMenu6.add(this.jMenuItem19);

		this.jMenuBar1.add(this.jMenu6);

		this.jMenu7.setMnemonic('E');
		this.jMenu7.setText("\u4e8b\u4ef6\u6a21\u578b(E)");

		this.jMenuItem20.setMnemonic('A');
		this.jMenuItem20.setText("\u52a8\u4f5c\u4e8b\u4ef6(A)");
		this.jMenu7.add(this.jMenuItem20);

		this.jMenuItem21.setMnemonic('K');
		this.jMenuItem21.setText("\u952e\u76d8\u4e8b\u4ef6(K)");
		this.jMenu7.add(this.jMenuItem21);

		this.jMenuItem22.setMnemonic('M');
		this.jMenuItem22.setText("\u9f20\u6807\u4e8b\u4ef6(M)");
		this.jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem22ActionPerformed(evt);
			}
		});
		this.jMenu7.add(this.jMenuItem22);
		this.jMenu7.add(this.jSeparator7);

		this.jMenuItem23.setMnemonic('F');
		this.jMenuItem23.setText("\u7a97\u53e3\u4e8b\u4ef6(F)");
		this.jMenu7.add(this.jMenuItem23);

		this.jMenuItem24.setMnemonic('S');
		this.jMenuItem24.setText("\u4e8b\u4ef6\u9002\u914d\u5668(S)");
		this.jMenu7.add(this.jMenuItem24);
		this.jMenu7.add(this.jSeparator8);

		this.jMenuItem25.setMnemonic('C');
		this.jMenuItem25.setText("\u9009\u9879\u4e8b\u4ef6(C)");
		this.jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem25ActionPerformed(evt);
			}
		});
		this.jMenu7.add(this.jMenuItem25);

		this.jMenuBar1.add(this.jMenu7);

		setJMenuBar(this.jMenuBar1);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(this.jLabel1)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				12,
																				12,
																				12)
																		.add(
																				this.jScrollPane1,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				476,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().add(this.jLabel1).addPreferredGap(
						org.jdesktop.layout.LayoutStyle.RELATED).add(
						this.jScrollPane1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 337,
						Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {
		this.jTextArea1.setText("");
		try {
			File file = new File(
					"src/main/java/edu/frank/swing/framework/JGUISource/JNeOrderTableUI.java");
			FileReader fr = new FileReader(file);
			this.jTextArea1.read(fr, null);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "UIUI", "",
					JOptionPane.WARNING_MESSAGE);
		}
		JNeOrderTableUI neOrderTableUI = new JNeOrderTableUI();
		java.awt.Window win = javax.swing.SwingUtilities.windowForComponent(neOrderTableUI);
		if (win != null && win instanceof javax.swing.JFrame) {
			javax.swing.JFrame frame = (javax.swing.JFrame) win;
			/*frame.addWindowListener(new WindowAdapter() {

				@Override
				public void windowClosed(WindowEvent e) {
					logger.error("Window[edu.frank.swing.framework.JGUISource.JNeOrderTableUI] will be closed! ");
					try {
						Thread.sleep(10 * 1000);
					} catch (InterruptedException e1) {
						logger.error("Fail to close Window[edu.frank.swing.framework.JGUISource.JNeOrderTableUI]", e1);
						//e1.printStackTrace();
					}
					super.windowClosed(e);
				}
			});*/
			frame.pack();
			frame.setVisible(true);

		}
	}

	private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {
		this.jTextArea1.setText("");
		try {
			File file = new File(
					"src/main/java/edu/frank/swing/framework/JGUISource/MouseEventUI.java");
			FileReader fr = new FileReader(file);
			this.jTextArea1.read(fr, null);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(this, "", "",
					JOptionPane.WARNING_MESSAGE);
		}
		MouseEventUI mouseEventUI = new MouseEventUI();
		mouseEventUI.setVisible(true);
	}

	private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
		// TODO 
	}//GEN-LAST:event_jMenuItem31ActionPerformed

	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
		// TODO 
		this.jTextArea1.setText("");
		try {
			File file = new File(
					"src/main/java/edu/frank/swing/framework/JGUISource/JTabbedPaneDemo.java");
			FileReader fr = new FileReader(file);
			this.jTextArea1.read(fr, null);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, ",!");
		}
		JTabbedPaneDemo frm = new JTabbedPaneDemo();
		frm.setVisible(true);
	}//GEN-LAST:event_jMenuItem8ActionPerformed

	private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
		this.jTextArea1.setText("");
		try {
			File file = new File(
					"src/main/java/edu/frank/swing/framework/JGUISource/JFileChooserDemo.java");
			FileReader fr = new FileReader(file);
			this.jTextArea1.read(fr, null);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, ",!");
		}
		JFileChooserDemo frm = new JFileChooserDemo();
		frm.setVisible(true);
		// TODO 
	}//GEN-LAST:event_jMenuItem38ActionPerformed

	private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
		this.jTextArea1.setText("");
		try {
			File file = new File("src/org/yoyudeng/JGUISource/JTableDemo.java");
			FileReader fr = new FileReader(file);
			this.jTextArea1.read(fr, null);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, ",!");
		}
		JTableDemo frm = new JTableDemo();
		frm.setVisible(true);
		// TODO 
	}//GEN-LAST:event_jMenuItem37ActionPerformed

	private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
		this.jTextArea1.setText("");
		try {
			File file = new File("src/org/yoyudeng/JGUISource/JSliderDemo.java");
			FileReader fr = new FileReader(file);
			this.jTextArea1.read(fr, null);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, ",!");
		}
		JSliderDemo frm = new JSliderDemo();
		frm.setVisible(true);
		// TODO 
	}//GEN-LAST:event_jMenuItem35ActionPerformed

	private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
		this.jTextArea1.setText("");
		try {
			File file = new File("src/org/yoyudeng/JGUISource/JTreeDemo.java");
			FileReader fr = new FileReader(file);
			this.jTextArea1.read(fr, null);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, ",!");
		}
		JTreeDemo frm = new JTreeDemo();
		frm.setVisible(true);
		// TODO 
	}//GEN-LAST:event_jMenuItem40ActionPerformed

	private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
		this.jTextArea1.setText("");
		try {
			File file = new File(
					"src/org/yoyudeng/JGUISource/JColorChooserDemo.java");
			FileReader fr = new FileReader(file);
			this.jTextArea1.read(fr, null);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, ",!");
		}
		JColorChooserDemo frm = new JColorChooserDemo();
		frm.setVisible(true);
		// TODO 
	}//GEN-LAST:event_jMenuItem39ActionPerformed

	private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
		this.jTextArea1.setText("");
		try {
			File file = new File(
					"src/org/yoyudeng/JGUISource/JProgressBarDemo.java");
			FileReader fr = new FileReader(file);
			this.jTextArea1.read(fr, null);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, ",!");
		}
		JProgressBarDemo frm = new JProgressBarDemo();
		frm.setVisible(true);
		// TODO 
	}//GEN-LAST:event_jMenuItem36ActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
		JSwingMain frm = new JSwingMain();
		frm.setVisible(true);
		dispose();
		// TODO 
	}//GEN-LAST:event_jMenuItem1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JGui().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenu jMenu6;
	private javax.swing.JMenu jMenu7;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem10;
	private javax.swing.JMenuItem jMenuItem11;
	private javax.swing.JMenuItem jMenuItem12;
	private javax.swing.JMenuItem jMenuItem13;
	private javax.swing.JMenuItem jMenuItem14;
	private javax.swing.JMenuItem jMenuItem15;
	private javax.swing.JMenuItem jMenuItem16;
	private javax.swing.JMenuItem jMenuItem17;
	private javax.swing.JMenuItem jMenuItem18;
	private javax.swing.JMenuItem jMenuItem19;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem20;
	private javax.swing.JMenuItem jMenuItem21;
	private javax.swing.JMenuItem jMenuItem22;
	private javax.swing.JMenuItem jMenuItem23;
	private javax.swing.JMenuItem jMenuItem24;
	private javax.swing.JMenuItem jMenuItem25;
	private javax.swing.JMenuItem jMenuItem26;
	private javax.swing.JMenuItem jMenuItem27;
	private javax.swing.JMenuItem jMenuItem28;
	private javax.swing.JMenuItem jMenuItem29;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem30;
	private javax.swing.JMenuItem jMenuItem31;
	private javax.swing.JMenuItem jMenuItem32;
	private javax.swing.JMenuItem jMenuItem33;
	private javax.swing.JMenuItem jMenuItem34;
	private javax.swing.JMenuItem jMenuItem35;
	private javax.swing.JMenuItem jMenuItem36;
	private javax.swing.JMenuItem jMenuItem37;
	private javax.swing.JMenuItem jMenuItem38;
	private javax.swing.JMenuItem jMenuItem39;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem40;
	private javax.swing.JMenuItem jMenuItem41;
	private javax.swing.JMenuItem jMenuItem42;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JMenuItem jMenuItem9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator10;
	private javax.swing.JSeparator jSeparator11;
	private javax.swing.JSeparator jSeparator12;
	private javax.swing.JSeparator jSeparator13;
	private javax.swing.JSeparator jSeparator14;
	private javax.swing.JSeparator jSeparator15;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JSeparator jSeparator5;
	private javax.swing.JSeparator jSeparator6;
	private javax.swing.JSeparator jSeparator7;
	private javax.swing.JSeparator jSeparator8;
	private javax.swing.JSeparator jSeparator9;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables
	private int m_height, m_width;
	private Toolkit toolkit = getToolkit();
}