/*
 * JProgressBarUI1.java
 *
 * Created on __DATE__, __TIME__
 */

package edu.frank.swing.framework.JGUISource;



/**
 *
 * @author  __USER__
 */
public class JProgressBarUI1 extends javax.swing.JPanel {

	private javax.swing.JWindow parentUI;

	class Task extends javax.swing.SwingWorker<Void, Void> {

		/* (non-Javadoc)
		 * @see javax.swing.SwingWorker#doInBackground()
		 */
		@Override
		protected Void doInBackground() throws Exception {
			// TODO Auto-generated method stub
			return null;
		}

	}

	/** Creates new form JProgressBarUI1 */
	public JProgressBarUI1() {
		initComponents();
		try {
			loadUI();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void loadUI() throws Exception {
		this.parentUI = new javax.swing.JWindow();
		this.parentUI.setSize(new java.awt.Dimension(269,67));
		java.awt.Container container = this.parentUI.getContentPane();
		container.add(this);
		this.parentUI.setAlwaysOnTop(true);
		this.parentUI.setVisible(true);
	}

	private void formMouseClicked(java.awt.event.MouseEvent evt) {
		if (evt != null) {
			if (evt.getClickCount() == 2) {
				if (this.parentUI != null) {
					this.parentUI.dispose();
				}
			}
		}
	}

	public static void main(String[] args) {
        //Schedule a job for the event-dispatching thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new JProgressBarUI1();
            }
        });
    }

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		this.progressBar = new javax.swing.JProgressBar();
		this.labMsg = new javax.swing.JLabel();

		addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				formMouseClicked(evt);
			}
		});

		this.progressBar.setToolTipText("\u8fdb\u5ea6\u4fe1\u606f");
		this.progressBar.setPreferredSize(new java.awt.Dimension(245, 14));

		this.labMsg.setText("\u8fdb\u5ea6\u4fe1\u606f . . .");
		this.labMsg.setToolTipText("\u8fdb\u5ea6\u4fe1\u606f");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																this.progressBar,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																245,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(this.labMsg))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(this.labMsg)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												this.progressBar,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents



	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel labMsg;
	private javax.swing.JProgressBar progressBar;
	// End of variables declaration//GEN-END:variables

}