/*
 * PowerSwingApp.java
 *
 * Created on __DATE__, __TIME__
 */

package edu.frank.swing.framework.JGUISource;

/**
 *
 * @author  __USER__
 */
public class PowerSwingApp extends javax.swing.JFrame {

	/** Creates new form PowerSwingApp */
	public PowerSwingApp() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		desktopPane = new javax.swing.JDesktopPane();
		aInternalFrame = new javax.swing.JInternalFrame();
		testPanel = new javax.swing.JPanel();
		myFileChooser = new javax.swing.JFileChooser();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		openMenuItem = new javax.swing.JMenuItem();
		saveMenuItem = new javax.swing.JMenuItem();
		saveAsMenuItem = new javax.swing.JMenuItem();
		exitMenuItem = new javax.swing.JMenuItem();
		editMenu = new javax.swing.JMenu();
		cutMenuItem = new javax.swing.JMenuItem();
		copyMenuItem = new javax.swing.JMenuItem();
		pasteMenuItem = new javax.swing.JMenuItem();
		deleteMenuItem = new javax.swing.JMenuItem();
		helpMenu = new javax.swing.JMenu();
		contentMenuItem = new javax.swing.JMenuItem();
		aboutMenuItem = new javax.swing.JMenuItem();
		CustomizedMenu = new javax.swing.JMenu();
		jMenuItemInternalFramA = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("MDI Frame");
		setName("mdiFrame");

		aInternalFrame.setMinimumSize(new java.awt.Dimension(0, 0));
		aInternalFrame.setNormalBounds(new java.awt.Rectangle(0, 0, 400, 279));
		aInternalFrame.setPreferredSize(new java.awt.Dimension(400, 279));
		aInternalFrame.setVisible(true);
		aInternalFrame.getContentPane().setLayout(null);

		testPanel.setLayout(null);

		myFileChooser.setPreferredSize(new java.awt.Dimension(370, 230));
		testPanel.add(myFileChooser);
		myFileChooser.setBounds(10, 10, 220, 10);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.setPreferredSize(new java.awt.Dimension(300, 100));
		jScrollPane1.setViewportView(jTable1);

		testPanel.add(jScrollPane1);
		jScrollPane1.setBounds(30, 130, 500, 160);

		aInternalFrame.getContentPane().add(testPanel);
		testPanel.setBounds(10, 10, 790, 310);

		aInternalFrame.setBounds(0, 0, 820, 360);
		desktopPane.add(aInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

		fileMenu.setText("File");

		openMenuItem.setText("Open");
		fileMenu.add(openMenuItem);

		saveMenuItem.setText("Save");
		fileMenu.add(saveMenuItem);

		saveAsMenuItem.setText("Save As ...");
		fileMenu.add(saveAsMenuItem);

		exitMenuItem.setText("Exit");
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(exitMenuItem);

		menuBar.add(fileMenu);

		editMenu.setText("Edit");

		cutMenuItem.setText("Cut");
		editMenu.add(cutMenuItem);

		copyMenuItem.setText("Copy");
		editMenu.add(copyMenuItem);

		pasteMenuItem.setText("Paste");
		editMenu.add(pasteMenuItem);

		deleteMenuItem.setText("Delete");
		editMenu.add(deleteMenuItem);

		menuBar.add(editMenu);

		helpMenu.setText("Help");

		contentMenuItem.setText("Contents");
		helpMenu.add(contentMenuItem);

		aboutMenuItem.setText("About");
		helpMenu.add(aboutMenuItem);

		menuBar.add(helpMenu);

		CustomizedMenu
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"src/main/resources/edu/frank/swing/picture/Backb.gif")));
		CustomizedMenu.setText("Customized");

		jMenuItemInternalFramA.setMnemonic('A');
		jMenuItemInternalFramA.setText("AInternalFrame");
		CustomizedMenu.add(jMenuItemInternalFramA);

		menuBar.add(CustomizedMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 820,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 362,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}//GEN-LAST:event_exitMenuItemActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PowerSwingApp().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu CustomizedMenu;
	private javax.swing.JInternalFrame aInternalFrame;
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JMenuItem contentMenuItem;
	private javax.swing.JMenuItem copyMenuItem;
	private javax.swing.JMenuItem cutMenuItem;
	private javax.swing.JMenuItem deleteMenuItem;
	private javax.swing.JDesktopPane desktopPane;
	private javax.swing.JMenu editMenu;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JMenuItem jMenuItemInternalFramA;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JFileChooser myFileChooser;
	private javax.swing.JMenuItem openMenuItem;
	private javax.swing.JMenuItem pasteMenuItem;
	private javax.swing.JMenuItem saveAsMenuItem;
	private javax.swing.JMenuItem saveMenuItem;
	private javax.swing.JPanel testPanel;
	// End of variables declaration//GEN-END:variables

}