/*
 * Software License
 * The file Library is
 * Copyright (C) 2010-2011 Hotel1802 Technologies Studio All Right Reserved .
 *
 * By obtaining,using,and/or copying this software and/or its associated
 * documentation, you agree that you have read, understood, and will comply
 * with the following terms and conditions :
 *
 * Permission to use, copy, modify, and distribute this file and its associated
 * documentation for any purpose and without fee is hereby granted, provide that
 * the above copyright notice appears in all copies, and that both that copyright
 * notice and this permission ontice appear in supporting documentation, and that
 * the name of Hotel802 or the author not be used in advertising or publicity
 * pertaining to distribution of the file without specific, written prior permission .
 *
 */
/**
 * Copyright : Hotel1802 All Right Reserved.
 * JDK Version : 1.6.10
 * Project : JavaBasic
 * Package : com.frank.swing.framework
 * File Name : JSwingMain.form / JSwingMain.java
 * File Version : 1.0.0.0
 *
 *
 * Author : Frank
 * Date : 2011-05-04
 * History :
 * <Name>				<Date>				<Content>
 *
 */

package edu.frank.swing.framework;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.ImageIcon;

import org.apache.log4j.Logger;

import edu.frank.log4j.Log4JConfig;
import edu.frank.swing.framework.JBasicSource.JBasic;
import edu.frank.swing.framework.JGUISource.JGui;

/**
 *
 * <p>
 * Main swing framwork entrence, it's a <code>JFrame</code> intance but not
 * including the border.
 * </p>
 *
 * @author Frank
 * @Version JavaBasic 1.0.0.0
 */
public class JSwingMain extends javax.swing.JFrame {

	/**
	 * Class serialized id.
	 *
	 * @since JavaBasic 1.0.0.0
	 */
	private static final long serialVersionUID = -5904503139137654821L;

	/**
	 * Logger record object
	 *
	 * @since JavaBasic 1.0.0.0
	 */
	private static final Logger logger = Log4JConfig
			.getLogger(JSwingMain.class);

	/**
	 *
	 * construct a new <code>JSwingMain</code> instance for class
	 *
	 * @since JavaBasic 1.0.0.0
	 */
	public JSwingMain() {
		initComponents();

		// force the frame in the center of the window
		m_width = getWidth();
		m_height = getHeight();
		int x = (toolkit.getScreenSize().width - m_width) / 2;
		int y = (toolkit.getScreenSize().height - m_height) / 2;
		this.setBounds(x, y, m_width, m_height);
		getContentPane().setBackground(Color.WHITE);
		setAlwaysOnTop(true);
		setVisible(true);

		// add window closing listener
		addWindowListener(new WindowAdapter() {
			/*
			 * (non-Javadoc)
			 *
			 * @see
			 * java.awt.event.WindowAdapter#windowOpened(java.awt.event.WindowEvent
			 * )
			 */
			@Override
			public void windowOpened(WindowEvent e) {
				logger.debug("Java Learning System have been start!");
				super.windowOpened(e);
			}

			/*
			 * (non-Javadoc)
			 *
			 * @see
			 * java.awt.event.WindowAdapter#windowClosing(java.awt.event.WindowEvent
			 * )
			 */
			@Override
			public void windowClosing(WindowEvent e) {
				logger.debug(JSwingMain.class.getSimpleName() + " will dispose !");
				super.windowClosing(e);
			}

		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="  ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Java\u57fa\u7840\u5b66\u4e60");
		setResizable(false);
		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage(
				"src/main/resources/edu/frank/swing/picture/javagif.gif")));

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel1Layout.createSequentialGroup().add(10, 10, 10).add(
						jLabel1,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jLabel1,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		jLabel2.setFont(new java.awt.Font("Serif", 1, 24));
		jLabel2.setForeground(new java.awt.Color(0, 0, 255));
		jLabel2.setText("\u4f60\u60f3\u5b66\u4e60JAVA\u5417\uff1f");

		jLabel3.setFont(new java.awt.Font("Serif", 1, 24));
		jLabel3.setForeground(new java.awt.Color(0, 0, 255));
		jLabel3.setText("\u8bf7\u4ece\u8fd9\u91cc\u5f00\u59cb\u5427!");

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"\u5b66\u4e60\u5185\u5bb9",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Dialog", 0, 13), new java.awt.Color(0, 0,
						255)));
		jButton1.setText("JAVA\u8bed\u6cd5");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("JAVAGUI");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().add(32, 32, 32).add(
						jButton1).add(27, 27, 27).add(jButton2)
						.addContainerGap(37, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel2Layout
										.createSequentialGroup()
										.add(45, 45, 45)
										.add(
												jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																jButton2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																48,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																jButton1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																49,
																Short.MAX_VALUE))
										.addContainerGap(56, Short.MAX_VALUE)));

		jLabel4.setFont(new java.awt.Font("", 0, 14));
		jLabel4.setText("CopyRight (C) 2007-2008 yoyudeng");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(26, 26, 26)
										.add(
												jPanel1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												119,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(55, 55, 55)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				jPanel2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.add(
																layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING)
																		.add(
																				layout
																						.createSequentialGroup()
																						.add(
																								jLabel2)
																						.addContainerGap(
																								87,
																								Short.MAX_VALUE))
																		.add(
																				org.jdesktop.layout.GroupLayout.TRAILING,
																				layout
																						.createSequentialGroup()
																						.addPreferredGap(
																								org.jdesktop.layout.LayoutStyle.RELATED)
																						.add(
																								jLabel3)
																						.add(
																								66,
																								66,
																								66)))))
						.add(
								org.jdesktop.layout.GroupLayout.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(126, Short.MAX_VALUE)
										.add(
												jLabel4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												252,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(122, 122, 122)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																jPanel1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																173,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				48,
																				48,
																				48)
																		.add(
																				jLabel2,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				48,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(
																				19,
																				19,
																				19)
																		.add(
																				jLabel3)))
										.add(4, 4, 4)
										.add(
												jPanel2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE).add(jLabel4)
										.addContainerGap()));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		JGui frm = new JGui();
		logger.debug(frm.getClass().getSimpleName() + " will start !");
		frm.setVisible(true);
		logger.debug(JSwingMain.class.getSimpleName() + " dispose !");
		dispose();
		// TODO 
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		JBasic frm = new JBasic();
		logger.debug(frm.getClass().getSimpleName() + " will start !");
		frm.setVisible(true);
		logger.debug(JSwingMain.class.getSimpleName() + " dispose !");
		dispose();
		// TODO 
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JSwingMain().setVisible(true);
			}
		});
	}

	//  - //GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// //GEN-END:variables
	private int m_height, m_width;
	private Toolkit toolkit = getToolkit();
}